import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Footer from '../components/Footer'
import Gallery from '../components/Gallery'
import GraphicDesign from '../components/GraphicDesign'
import HeaderMain from '../components/HeaderMain'
import Standout from '../components/Standout'
import { Testimonials } from '../components/Testimonials'




export default function Home() {
  return (
    <>
      <Head>
        <title>Sunnyside</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={''}>
      <HeaderMain/>
      <About/>
      <Standout/>
      <GraphicDesign/>
      <Testimonials/>
      <Gallery/>
      <Footer/>
     
      </main>
    </>
  )
}
